# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'rxsg_ui_v1QITxVn.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(370, 600)
        MainWindow.setMinimumSize(QSize(370, 600))
        MainWindow.setMaximumSize(QSize(370, 600))
        self.otherPara = QAction(MainWindow)
        self.otherPara.setObjectName(u"otherPara")
        self.exitAct = QAction(MainWindow)
        self.exitAct.setObjectName(u"exitAct")
        self.versionAct = QAction(MainWindow)
        self.versionAct.setObjectName(u"versionAct")
        self.aboutAct = QAction(MainWindow)
        self.aboutAct.setObjectName(u"aboutAct")
        self.getnewAction = QAction(MainWindow)
        self.getnewAction.setObjectName(u"getnewAction")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 351, 111))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 61, 21))
        self.leftUpX = QLineEdit(self.groupBox)
        self.leftUpX.setObjectName(u"leftUpX")
        self.leftUpX.setEnabled(False)
        self.leftUpX.setGeometry(QRect(60, 20, 91, 20))
        self.leftUpX.setReadOnly(True)
        self.leftUpY = QLineEdit(self.groupBox)
        self.leftUpY.setObjectName(u"leftUpY")
        self.leftUpY.setEnabled(False)
        self.leftUpY.setGeometry(QRect(160, 20, 91, 20))
        self.leftUpY.setReadOnly(True)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 50, 61, 21))
        self.rightDownX = QLineEdit(self.groupBox)
        self.rightDownX.setObjectName(u"rightDownX")
        self.rightDownX.setEnabled(False)
        self.rightDownX.setGeometry(QRect(60, 50, 91, 20))
        self.rightDownX.setReadOnly(True)
        self.rightDownY = QLineEdit(self.groupBox)
        self.rightDownY.setObjectName(u"rightDownY")
        self.rightDownY.setEnabled(False)
        self.rightDownY.setGeometry(QRect(160, 50, 91, 20))
        self.rightDownY.setReadOnly(True)
        self.setCoordinateZS = QPushButton(self.groupBox)
        self.setCoordinateZS.setObjectName(u"setCoordinateZS")
        self.setCoordinateZS.setGeometry(QRect(260, 20, 75, 21))
        self.hwndLine = QLineEdit(self.groupBox)
        self.hwndLine.setObjectName(u"hwndLine")
        self.hwndLine.setEnabled(False)
        self.hwndLine.setGeometry(QRect(70, 80, 181, 21))
        self.hwndLine.setReadOnly(True)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 80, 61, 21))
        self.setCoordinateYX = QPushButton(self.groupBox)
        self.setCoordinateYX.setObjectName(u"setCoordinateYX")
        self.setCoordinateYX.setGeometry(QRect(260, 50, 75, 21))
        self.getHwndButton = QPushButton(self.groupBox)
        self.getHwndButton.setObjectName(u"getHwndButton")
        self.getHwndButton.setGeometry(QRect(260, 80, 75, 23))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(6, 129, 361, 441))
        self.HJ_tab1 = QWidget()
        self.HJ_tab1.setObjectName(u"HJ_tab1")
        self.label_4 = QLabel(self.HJ_tab1)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 10, 61, 21))
        self.label_5 = QLabel(self.HJ_tab1)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(190, 10, 61, 21))
        self.label_6 = QLabel(self.HJ_tab1)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 40, 61, 21))
        self.label_7 = QLabel(self.HJ_tab1)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(190, 40, 61, 21))
        self.comboRoute = QComboBox(self.HJ_tab1)
        self.comboRoute.addItem("")
        self.comboRoute.addItem("")
        self.comboRoute.addItem("")
        self.comboRoute.addItem("")
        self.comboRoute.addItem("")
        self.comboRoute.setObjectName(u"comboRoute")
        self.comboRoute.setGeometry(QRect(70, 10, 91, 22))
        self.comboCommand = QComboBox(self.HJ_tab1)
        self.comboCommand.addItem("")
        self.comboCommand.addItem("")
        self.comboCommand.addItem("")
        self.comboCommand.addItem("")
        self.comboCommand.addItem("")
        self.comboCommand.setObjectName(u"comboCommand")
        self.comboCommand.setGeometry(QRect(250, 10, 91, 22))
        self.comboArm = QComboBox(self.HJ_tab1)
        self.comboArm.addItem("")
        self.comboArm.addItem("")
        self.comboArm.addItem("")
        self.comboArm.addItem("")
        self.comboArm.setObjectName(u"comboArm")
        self.comboArm.setGeometry(QRect(70, 40, 91, 22))
        self.comboPlayerNum = QComboBox(self.HJ_tab1)
        self.comboPlayerNum.addItem("")
        self.comboPlayerNum.addItem("")
        self.comboPlayerNum.addItem("")
        self.comboPlayerNum.addItem("")
        self.comboPlayerNum.setObjectName(u"comboPlayerNum")
        self.comboPlayerNum.setGeometry(QRect(250, 40, 91, 22))
        self.groupBox_2 = QGroupBox(self.HJ_tab1)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, 70, 351, 341))
        self.plainTextEdit = QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(3, 80, 291, 251))
        self.plainTextEdit.setReadOnly(True)
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 20, 61, 21))
        self.comboFromCity = QComboBox(self.groupBox_2)
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.addItem("")
        self.comboFromCity.setObjectName(u"comboFromCity")
        self.comboFromCity.setEnabled(False)
        self.comboFromCity.setGeometry(QRect(70, 20, 91, 22))
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(190, 20, 71, 21))
        self.label_10 = QLabel(self.groupBox_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 50, 61, 21))
        self.troopNum = QLineEdit(self.groupBox_2)
        self.troopNum.setObjectName(u"troopNum")
        self.troopNum.setEnabled(False)
        self.troopNum.setGeometry(QRect(70, 50, 91, 21))
        self.troopNum.setReadOnly(False)
        self.buttonStart = QPushButton(self.groupBox_2)
        self.buttonStart.setObjectName(u"buttonStart")
        self.buttonStart.setGeometry(QRect(300, 90, 41, 31))
        self.buttonPause = QPushButton(self.groupBox_2)
        self.buttonPause.setObjectName(u"buttonPause")
        self.buttonPause.setEnabled(False)
        self.buttonPause.setGeometry(QRect(300, 130, 41, 31))
        self.buttonClose = QPushButton(self.groupBox_2)
        self.buttonClose.setObjectName(u"buttonClose")
        self.buttonClose.setEnabled(False)
        self.buttonClose.setGeometry(QRect(300, 210, 41, 31))
        self.label_11 = QLabel(self.groupBox_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(190, 50, 61, 21))
        self.comboAcce = QComboBox(self.groupBox_2)
        self.comboAcce.addItem("")
        self.comboAcce.addItem("")
        self.comboAcce.setObjectName(u"comboAcce")
        self.comboAcce.setEnabled(False)
        self.comboAcce.setGeometry(QRect(250, 50, 91, 22))
        self.comboToCity = QComboBox(self.groupBox_2)
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.addItem("")
        self.comboToCity.setObjectName(u"comboToCity")
        self.comboToCity.setEnabled(False)
        self.comboToCity.setGeometry(QRect(250, 20, 91, 22))
        self.buttonGoOn = QPushButton(self.groupBox_2)
        self.buttonGoOn.setObjectName(u"buttonGoOn")
        self.buttonGoOn.setEnabled(False)
        self.buttonGoOn.setGeometry(QRect(300, 170, 41, 31))
        self.tabWidget.addTab(self.HJ_tab1, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_12 = QLabel(self.tab)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 10, 41, 21))
        self.fh_city1_x = QLineEdit(self.tab)
        self.fh_city1_x.setObjectName(u"fh_city1_x")
        self.fh_city1_x.setEnabled(False)
        self.fh_city1_x.setGeometry(QRect(50, 10, 51, 21))
        self.fh_city1_y = QLineEdit(self.tab)
        self.fh_city1_y.setObjectName(u"fh_city1_y")
        self.fh_city1_y.setEnabled(False)
        self.fh_city1_y.setGeometry(QRect(100, 10, 51, 21))
        self.fh_city1_type = QComboBox(self.tab)
        self.fh_city1_type.addItem("")
        self.fh_city1_type.addItem("")
        self.fh_city1_type.setObjectName(u"fh_city1_type")
        self.fh_city1_type.setGeometry(QRect(190, 10, 61, 21))
        self.fh_city1_set = QPushButton(self.tab)
        self.fh_city1_set.setObjectName(u"fh_city1_set")
        self.fh_city1_set.setGeometry(QRect(150, 10, 41, 23))
        self.fh_city1_num = QLineEdit(self.tab)
        self.fh_city1_num.setObjectName(u"fh_city1_num")
        self.fh_city1_num.setGeometry(QRect(300, 10, 41, 20))
        self.label_13 = QLabel(self.tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(260, 10, 31, 21))
        self.fh_city2_x = QLineEdit(self.tab)
        self.fh_city2_x.setObjectName(u"fh_city2_x")
        self.fh_city2_x.setEnabled(False)
        self.fh_city2_x.setGeometry(QRect(50, 40, 51, 21))
        self.fh_city2_type = QComboBox(self.tab)
        self.fh_city2_type.addItem("")
        self.fh_city2_type.addItem("")
        self.fh_city2_type.setObjectName(u"fh_city2_type")
        self.fh_city2_type.setGeometry(QRect(190, 40, 61, 21))
        self.fh_city2_set = QPushButton(self.tab)
        self.fh_city2_set.setObjectName(u"fh_city2_set")
        self.fh_city2_set.setGeometry(QRect(150, 40, 41, 23))
        self.label_14 = QLabel(self.tab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 40, 41, 21))
        self.fh_city2_y = QLineEdit(self.tab)
        self.fh_city2_y.setObjectName(u"fh_city2_y")
        self.fh_city2_y.setEnabled(False)
        self.fh_city2_y.setGeometry(QRect(100, 40, 51, 21))
        self.fh_city2_num = QLineEdit(self.tab)
        self.fh_city2_num.setObjectName(u"fh_city2_num")
        self.fh_city2_num.setGeometry(QRect(300, 40, 41, 20))
        self.label_15 = QLabel(self.tab)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(260, 40, 31, 21))
        self.fh_city3_x = QLineEdit(self.tab)
        self.fh_city3_x.setObjectName(u"fh_city3_x")
        self.fh_city3_x.setEnabled(False)
        self.fh_city3_x.setGeometry(QRect(50, 70, 51, 21))
        self.fh_city3_type = QComboBox(self.tab)
        self.fh_city3_type.addItem("")
        self.fh_city3_type.addItem("")
        self.fh_city3_type.setObjectName(u"fh_city3_type")
        self.fh_city3_type.setGeometry(QRect(190, 70, 61, 21))
        self.fh_city3_set = QPushButton(self.tab)
        self.fh_city3_set.setObjectName(u"fh_city3_set")
        self.fh_city3_set.setGeometry(QRect(150, 70, 41, 23))
        self.label_16 = QLabel(self.tab)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 70, 41, 21))
        self.fh_city3_y = QLineEdit(self.tab)
        self.fh_city3_y.setObjectName(u"fh_city3_y")
        self.fh_city3_y.setEnabled(False)
        self.fh_city3_y.setGeometry(QRect(100, 70, 51, 21))
        self.fh_city3_num = QLineEdit(self.tab)
        self.fh_city3_num.setObjectName(u"fh_city3_num")
        self.fh_city3_num.setGeometry(QRect(300, 70, 41, 20))
        self.label_17 = QLabel(self.tab)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(260, 70, 31, 21))
        self.fh_city4_x = QLineEdit(self.tab)
        self.fh_city4_x.setObjectName(u"fh_city4_x")
        self.fh_city4_x.setEnabled(False)
        self.fh_city4_x.setGeometry(QRect(50, 100, 51, 21))
        self.fh_city4_type = QComboBox(self.tab)
        self.fh_city4_type.addItem("")
        self.fh_city4_type.addItem("")
        self.fh_city4_type.setObjectName(u"fh_city4_type")
        self.fh_city4_type.setGeometry(QRect(190, 100, 61, 21))
        self.fh_city4_set = QPushButton(self.tab)
        self.fh_city4_set.setObjectName(u"fh_city4_set")
        self.fh_city4_set.setGeometry(QRect(150, 100, 41, 23))
        self.label_18 = QLabel(self.tab)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 100, 41, 21))
        self.fh_city4_y = QLineEdit(self.tab)
        self.fh_city4_y.setObjectName(u"fh_city4_y")
        self.fh_city4_y.setEnabled(False)
        self.fh_city4_y.setGeometry(QRect(100, 100, 51, 21))
        self.fh_city4_num = QLineEdit(self.tab)
        self.fh_city4_num.setObjectName(u"fh_city4_num")
        self.fh_city4_num.setGeometry(QRect(300, 100, 41, 20))
        self.label_19 = QLabel(self.tab)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(260, 100, 31, 21))
        self.fh_city5_x = QLineEdit(self.tab)
        self.fh_city5_x.setObjectName(u"fh_city5_x")
        self.fh_city5_x.setEnabled(False)
        self.fh_city5_x.setGeometry(QRect(50, 130, 51, 21))
        self.fh_city5_type = QComboBox(self.tab)
        self.fh_city5_type.addItem("")
        self.fh_city5_type.addItem("")
        self.fh_city5_type.setObjectName(u"fh_city5_type")
        self.fh_city5_type.setGeometry(QRect(190, 130, 61, 21))
        self.fh_city5_set = QPushButton(self.tab)
        self.fh_city5_set.setObjectName(u"fh_city5_set")
        self.fh_city5_set.setGeometry(QRect(150, 130, 41, 23))
        self.label_20 = QLabel(self.tab)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 130, 41, 21))
        self.fh_city5_y = QLineEdit(self.tab)
        self.fh_city5_y.setObjectName(u"fh_city5_y")
        self.fh_city5_y.setEnabled(False)
        self.fh_city5_y.setGeometry(QRect(100, 130, 51, 21))
        self.fh_city5_num = QLineEdit(self.tab)
        self.fh_city5_num.setObjectName(u"fh_city5_num")
        self.fh_city5_num.setGeometry(QRect(300, 130, 41, 20))
        self.label_21 = QLabel(self.tab)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(260, 130, 41, 21))
        self.fh_plaintext = QPlainTextEdit(self.tab)
        self.fh_plaintext.setObjectName(u"fh_plaintext")
        self.fh_plaintext.setGeometry(QRect(10, 180, 271, 221))
        self.fh_start = QPushButton(self.tab)
        self.fh_start.setObjectName(u"fh_start")
        self.fh_start.setGeometry(QRect(290, 180, 51, 31))
        self.fh_pause = QPushButton(self.tab)
        self.fh_pause.setObjectName(u"fh_pause")
        self.fh_pause.setEnabled(False)
        self.fh_pause.setGeometry(QRect(290, 220, 51, 31))
        self.fh_acce = QCheckBox(self.tab)
        self.fh_acce.setObjectName(u"fh_acce")
        self.fh_acce.setGeometry(QRect(10, 150, 101, 31))
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 370, 23))
        self.FuncMenu = QMenu(self.menubar)
        self.FuncMenu.setObjectName(u"FuncMenu")
        self.HelpMenu = QMenu(self.menubar)
        self.HelpMenu.setObjectName(u"HelpMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.FuncMenu.menuAction())
        self.menubar.addAction(self.HelpMenu.menuAction())
        self.FuncMenu.addAction(self.otherPara)
        self.FuncMenu.addSeparator()
        self.FuncMenu.addAction(self.exitAct)
        self.HelpMenu.addAction(self.versionAct)
        self.HelpMenu.addAction(self.aboutAct)
        self.HelpMenu.addAction(self.getnewAction)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u70ed\u8840\u4e09\u56fd\u811a\u672c\u8f85\u52a9", None))
        self.otherPara.setText(QCoreApplication.translate("MainWindow", u"\u901f\u5ea6", None))
        self.exitAct.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.versionAct.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u7248\u672c", None))
        self.aboutAct.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e\u8f6f\u4ef6", None))
        self.getnewAction.setText(QCoreApplication.translate("MainWindow", u"\u83b7\u53d6\u6700\u65b0\u7248\u672c", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u6e38\u620f\u754c\u9762\u5750\u6807", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u5de6\u4e0a\u89d2\uff1a", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u53f3\u4e0b\u89d2\uff1a", None))
        self.setCoordinateZS.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3\u53e5\u67c4\uff1a", None))
        self.setCoordinateYX.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.getHwndButton.setText(QCoreApplication.translate("MainWindow", u"\u83b7\u53d6", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u6218\u573a\u8def\u7ebf\uff1a", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u6307\u6325\u65b9\u6848\uff1a", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u519b\u961f\u65b9\u6848\uff1a", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u6218\u573a\u4eba\u6570\uff1a", None))
        self.comboRoute.setItemText(0, QCoreApplication.translate("MainWindow", u"\u8def\u7ebf\u4e00", None))
        self.comboRoute.setItemText(1, QCoreApplication.translate("MainWindow", u"\u8def\u7ebf\u4e8c", None))
        self.comboRoute.setItemText(2, QCoreApplication.translate("MainWindow", u"\u8def\u7ebf\u4e09", None))
        self.comboRoute.setItemText(3, QCoreApplication.translate("MainWindow", u"\u8def\u7ebf\u56db", None))
        self.comboRoute.setItemText(4, QCoreApplication.translate("MainWindow", u"\u8def\u7ebf\u4e94", None))

        self.comboRoute.setCurrentText(QCoreApplication.translate("MainWindow", u"\u8def\u7ebf\u4e00", None))
        self.comboRoute.setPlaceholderText("")
        self.comboCommand.setItemText(0, QCoreApplication.translate("MainWindow", u"\u7b80\u5355\u6218\u573a", None))
        self.comboCommand.setItemText(1, QCoreApplication.translate("MainWindow", u"\u7cbe\u82f1\u6218\u573a", None))
        self.comboCommand.setItemText(2, QCoreApplication.translate("MainWindow", u"\u56f0\u96be\u6218\u573a", None))
        self.comboCommand.setItemText(3, QCoreApplication.translate("MainWindow", u"\u6781\u96be\u6218\u573a", None))
        self.comboCommand.setItemText(4, QCoreApplication.translate("MainWindow", u"\u81ea\u5b9a\u4e49\uff08\u672a\u5b8c\uff09", None))

        self.comboArm.setItemText(0, QCoreApplication.translate("MainWindow", u"\u65b9\u6848\u4e00", None))
        self.comboArm.setItemText(1, QCoreApplication.translate("MainWindow", u"\u65b9\u6848\u4e8c", None))
        self.comboArm.setItemText(2, QCoreApplication.translate("MainWindow", u"\u65b9\u6848\u4e09", None))
        self.comboArm.setItemText(3, QCoreApplication.translate("MainWindow", u"\u65b9\u6848\u56db", None))

        self.comboPlayerNum.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboPlayerNum.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboPlayerNum.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboPlayerNum.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))

        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u6218\u573a\u4fe1\u606f\uff1a", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u57ce\u5e02\uff1a", None))
        self.comboFromCity.setItemText(0, QCoreApplication.translate("MainWindow", u"\u8944\u9633", None))
        self.comboFromCity.setItemText(1, QCoreApplication.translate("MainWindow", u"\u6a0a\u57ce", None))
        self.comboFromCity.setItemText(2, QCoreApplication.translate("MainWindow", u"\u897f\u9102\u7cbe\u5c71", None))
        self.comboFromCity.setItemText(3, QCoreApplication.translate("MainWindow", u"\u6cfe\u9633", None))
        self.comboFromCity.setItemText(4, QCoreApplication.translate("MainWindow", u"\u5b9b\u57ce", None))
        self.comboFromCity.setItemText(5, QCoreApplication.translate("MainWindow", u"\u9ad8\u9675", None))
        self.comboFromCity.setItemText(6, QCoreApplication.translate("MainWindow", u"\u6c5d\u5357", None))
        self.comboFromCity.setItemText(7, QCoreApplication.translate("MainWindow", u"\u5357\u9633", None))
        self.comboFromCity.setItemText(8, QCoreApplication.translate("MainWindow", u"\u988d\u5ddd", None))
        self.comboFromCity.setItemText(9, QCoreApplication.translate("MainWindow", u"\u897f\u534e", None))
        self.comboFromCity.setItemText(10, QCoreApplication.translate("MainWindow", u"\u9633\u7fdf", None))
        self.comboFromCity.setItemText(11, QCoreApplication.translate("MainWindow", u"\u6cb3\u5185", None))
        self.comboFromCity.setItemText(12, QCoreApplication.translate("MainWindow", u"\u65b0\u91ce", None))
        self.comboFromCity.setItemText(13, QCoreApplication.translate("MainWindow", u"\u6b66\u5e73", None))
        self.comboFromCity.setItemText(14, QCoreApplication.translate("MainWindow", u"\u9648\u7559", None))
        self.comboFromCity.setItemText(15, QCoreApplication.translate("MainWindow", u"\u4ed3\u4ead", None))
        self.comboFromCity.setItemText(16, QCoreApplication.translate("MainWindow", u"\u5e7f\u5b97", None))
        self.comboFromCity.setItemText(17, QCoreApplication.translate("MainWindow", u"\u4e0b\u66f2\u9633", None))
        self.comboFromCity.setItemText(18, QCoreApplication.translate("MainWindow", u"\u5de8\u9e7f", None))

        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u76ee\u6807\u57ce\u5e02\uff1a", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u519b\u961f\u6570\u91cf\uff1a", None))
        self.buttonStart.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb", None))
        self.buttonPause.setText(QCoreApplication.translate("MainWindow", u"\u6682\u505c", None))
        self.buttonClose.setText(QCoreApplication.translate("MainWindow", u"\u7ed3\u675f", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u52a0\u901f\u5956\u52b1\uff1a", None))
        self.comboAcce.setItemText(0, QCoreApplication.translate("MainWindow", u"\u5426", None))
        self.comboAcce.setItemText(1, QCoreApplication.translate("MainWindow", u"\u662f", None))

        self.comboToCity.setItemText(0, QCoreApplication.translate("MainWindow", u"\u6a0a\u57ce", None))
        self.comboToCity.setItemText(1, QCoreApplication.translate("MainWindow", u"\u897f\u9102\u7cbe\u5c71", None))
        self.comboToCity.setItemText(2, QCoreApplication.translate("MainWindow", u"\u6cfe\u9633", None))
        self.comboToCity.setItemText(3, QCoreApplication.translate("MainWindow", u"\u5b9b\u57ce", None))
        self.comboToCity.setItemText(4, QCoreApplication.translate("MainWindow", u"\u9ad8\u9675", None))
        self.comboToCity.setItemText(5, QCoreApplication.translate("MainWindow", u"\u6c5d\u5357", None))
        self.comboToCity.setItemText(6, QCoreApplication.translate("MainWindow", u"\u5357\u9633", None))
        self.comboToCity.setItemText(7, QCoreApplication.translate("MainWindow", u"\u988d\u5ddd", None))
        self.comboToCity.setItemText(8, QCoreApplication.translate("MainWindow", u"\u897f\u534e", None))
        self.comboToCity.setItemText(9, QCoreApplication.translate("MainWindow", u"\u9633\u7fdf", None))
        self.comboToCity.setItemText(10, QCoreApplication.translate("MainWindow", u"\u6cb3\u5185", None))
        self.comboToCity.setItemText(11, QCoreApplication.translate("MainWindow", u"\u65b0\u91ce", None))
        self.comboToCity.setItemText(12, QCoreApplication.translate("MainWindow", u"\u6b66\u5e73", None))
        self.comboToCity.setItemText(13, QCoreApplication.translate("MainWindow", u"\u9648\u7559", None))
        self.comboToCity.setItemText(14, QCoreApplication.translate("MainWindow", u"\u4ed3\u4ead", None))
        self.comboToCity.setItemText(15, QCoreApplication.translate("MainWindow", u"\u5e7f\u5b97", None))
        self.comboToCity.setItemText(16, QCoreApplication.translate("MainWindow", u"\u4e0b\u66f2\u9633", None))
        self.comboToCity.setItemText(17, QCoreApplication.translate("MainWindow", u"\u5de8\u9e7f", None))

        self.buttonGoOn.setText(QCoreApplication.translate("MainWindow", u"\u7ee7\u7eed", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HJ_tab1), QCoreApplication.translate("MainWindow", u"\u9ec4\u5dfe\u6218\u573a", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u57ce\u5e021\uff1a", None))
        self.fh_city1_type.setItemText(0, QCoreApplication.translate("MainWindow", u"\u519b\u961f\u6218", None))
        self.fh_city1_type.setItemText(1, QCoreApplication.translate("MainWindow", u"\u6597\u5c06\u6218", None))

        self.fh_city1_set.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.fh_city1_num.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u6b21\u6570\uff1a", None))
        self.fh_city2_type.setItemText(0, QCoreApplication.translate("MainWindow", u"\u519b\u961f\u6218", None))
        self.fh_city2_type.setItemText(1, QCoreApplication.translate("MainWindow", u"\u6597\u5c06\u6218", None))

        self.fh_city2_set.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u57ce\u5e022\uff1a", None))
        self.fh_city2_num.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\u6b21\u6570\uff1a", None))
        self.fh_city3_type.setItemText(0, QCoreApplication.translate("MainWindow", u"\u519b\u961f\u6218", None))
        self.fh_city3_type.setItemText(1, QCoreApplication.translate("MainWindow", u"\u6597\u5c06\u6218", None))

        self.fh_city3_set.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\u57ce\u5e023\uff1a", None))
        self.fh_city3_num.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u6b21\u6570\uff1a", None))
        self.fh_city4_type.setItemText(0, QCoreApplication.translate("MainWindow", u"\u519b\u961f\u6218", None))
        self.fh_city4_type.setItemText(1, QCoreApplication.translate("MainWindow", u"\u6597\u5c06\u6218", None))

        self.fh_city4_set.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u57ce\u5e024\uff1a", None))
        self.fh_city4_num.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\u6b21\u6570\uff1a", None))
        self.fh_city5_type.setItemText(0, QCoreApplication.translate("MainWindow", u"\u519b\u961f\u6218", None))
        self.fh_city5_type.setItemText(1, QCoreApplication.translate("MainWindow", u"\u6597\u5c06\u6218", None))

        self.fh_city5_set.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"\u57ce\u5e025\uff1a", None))
        self.fh_city5_num.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"\u6b21\u6570\uff1a", None))
        self.fh_start.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb", None))
        self.fh_pause.setText(QCoreApplication.translate("MainWindow", u"\u6682\u505c", None))
        self.fh_acce.setText(QCoreApplication.translate("MainWindow", u"\u4f7f\u7528\u793c\u91d1\u52a0\u901f", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u70fd\u706b\u6218\u573a", None))
        self.FuncMenu.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.HelpMenu.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
    # retranslateUi